[package]
org = "shamiso"
name = "International_Service"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[container.image]
repository = "wso2inc"
name = "hello"
tag = "v0.1.0"

